name: deployment
on:
  push:
    branches: [main]
concurrency: production_environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install NPM Dependencies
        run: npm clean-install

      - name: Build
        run: npm run predeploy

      - name: Deploy to GitHub Pages
        run: npm run deploy
