name: pipeline
on: pull_request

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install NPM Dependencies
        run: npm clean-install

      - name: Code Style CSS & JS
        run: npm run check-style
